spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 5MB       # 개별 파일 최대 크기
      max-request-size: 20MB    # 전체 요청 최대 크기
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.time_zone: Asia/Seoul
  jackson:
    time-zone: Asia/Seoul
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  config:
    import: optional:file:.env[.properties]
  web:
    resources:
      static-locations: classpath:/static/, file:/var/www/uploads/
  datasource:
    url: jdbc:mariadb://localhost:3306/portfolio?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Seoul
    username: ENC(baB8CukL9Rz5rbaZ98en5A==)
    password: ENC(8lNr4CEDkS++bweMyVVPyBfr6bAQeevP)
    hikari:
      pool-name: HikariPool
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      data-source-properties:
        useUnicode: true
        characterEncoding: utf8mb4
        characterSetResults: utf8mb4
  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 1

logging:
  level:
    org.springframework.jdbc: DEBUG
    com.zaxxer.hikari: DEBUG
    org.jooq: DEBUG

file:
  upload-dir: /var/www/html/portfolio_api/uploads       # 실제 업로드 저장 경로

jwt:
  secret-key: qwhDhLFtrxWfs951DcODc3PWtwTNxU6vvwAX

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

server:
  port: 9090
  shutdown: graceful
  servlet:
    context-path: /
  ssl:
    enabled: false

#server:
#  port: 9090
#  ssl:
#    enabled: true
#    key-store: file:/app/ssl/keystore.p12
#    key-store-type: PKCS12
#    key-store-password:


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html # Swagger UI ??
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    tags-sorter: alpha
  paths-to-match: /**
  packages-to-scan: com.portfolio.ktboot
  default-consumes-media-type: application/json
  default-produces-media-type: application/json




---



spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 5MB       # 개별 파일 최대 크기
      max-request-size: 20MB    # 전체 요청 최대 크기
  config:
    activate:
      on-profile: test
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.time_zone: Asia/Seoul
  jackson:
    time-zone: Asia/Seoul
  web:
    resources:
      static-locations: classpath:/static/, file:/var/www/uploads/
  datasource:
    url: jdbc:mariadb://localhost:3306/portfolio?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Seoul
    username: ENC(baB8CukL9Rz5rbaZ98en5A==)
    password: ENC(8lNr4CEDkS++bweMyVVPyBfr6bAQeevP)
    hikari:
      pool-name: HikariPool
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      data-source-properties:
        useUnicode: true
        characterEncoding: utf8mb4
        characterSetResults: utf8mb4
  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 1
    schemas: portfolio
logging:
  level:
    org.springframework.jdbc: DEBUG
    com.zaxxer.hikari: DEBUG
    org.jooq: DEBUG

jwt:
  secret-key: qwhDhLFtrxWfs951DcODc3PWtwTNxU6vvwAX



jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
    algorithm: PBEWithMD5AndDES
    pool-size: 4


server:
  port: 9090
  shutdown: graceful
  servlet:
    context-path: /
  ssl:
    enabled: false

#server:
#  port: 9090
#  ssl:
#    enabled: true
#    key-store: file:/app/ssl/keystore.p12
#    key-store-type: PKCS12
#    key-store-password:


---

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 5MB       # 개별 파일 최대 크기
      max-request-size: 20MB    # 전체 요청 최대 크기
  config:
    activate:
      on-profile: docker
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.time_zone: Asia/Seoul
  jackson:
    time-zone: Asia/Seoul
  web:
    resources:
      static-locations: classpath:/static/, file:/var/www/uploads/
  datasource:
    url: jdbc:mariadb://host.docker.internal:3306/portfolio?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Seoul
    username: ENC(A6bs9PFdqSREKHU6ZT2X/A==)
    password: ENC(FaWhFpcpyykwCtIcbPTDqw==)
    hikari:
      pool-name: HikariPool
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      data-source-properties:
        useUnicode: true
        characterEncoding: utf8mb4
        characterSetResults: utf8mb4
  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 1
    schemas: portfolio
logging:
  level:
    org.springframework.jdbc: DEBUG
    com.zaxxer.hikari: DEBUG
    org.jooq: DEBUG

jwt:
  secret-key: qwhDhLFtrxWfs951DcODc3PWtwTNxU6vvwAX

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

server:
  port: 9090
  shutdown: graceful
  servlet:
    context-path: /
  ssl:
    enabled: false

#server:
#  port: 9090
#  ssl:
#    enabled: true
#    key-store: file:/app/ssl/keystore.p12
#    key-store-type: PKCS12
#    key-store-password:


---


spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 5MB       # 개별 파일 최대 크기
      max-request-size: 20MB    # 전체 요청 최대 크기
  config:
    activate:
      on-profile: aws
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.time_zone: Asia/Seoul
  jackson:
    time-zone: Asia/Seoul
  web:
    resources:
      static-locations: classpath:/static/, file:/var/www/uploads/
  datasource:
    url: jdbc:mariadb://mariadb:3306/portfolio?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Seoul
    username: ENC(A6bs9PFdqSREKHU6ZT2X/A==)
    password: ENC(C14tHl6vPVXt82drZl0y8R5biATpO5Tt)
    hikari:
      pool-name: HikariPool
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      data-source-properties:
        useUnicode: true
        characterEncoding: utf8mb4
        characterSetResults: utf8mb4
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 1
    schemas: portfolio
logging:
  level:
    org.springframework.jdbc: DEBUG
    com.zaxxer.hikari: DEBUG
    org.jooq: DEBUG

jwt:
  secret-key: qwhDhLFtrxWfs951DcODc3PWtwTNxU6vvwAX

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}


server:
  port: 9090
  shutdown: graceful
  servlet:
    context-path: /
  ssl:
    enabled: false

#server:
#  port: 9090
#  ssl:
#    enabled: true
#    key-store: file:/app/ssl/keystore.p12
#    key-store-type: PKCS12
#    key-store-password:

aws:
  s3:
    bucket: portfolio-web
    region: ap-northeast-2
    access-key: ENC(VGhkUYW4GkGdpaNj6t5F6cHrZdsJ3/Fhmw1wSmTHusQ=)
    secret-key: ENC(WmNFL2CDAnBcWL+t5jfCTLqeuAius4h4aWRb3Qt2UY6hWH4Y4l0AJvPcBbJ96uqtrArqvmbT1YA=)

---


spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 5MB       # 개별 파일 최대 크기
      max-request-size: 20MB    # 전체 요청 최대 크기
  config:
    activate:
      on-profile: operation
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.time_zone: Asia/Seoul
  jackson:
    time-zone: Asia/Seoul
  web:
    resources:
      static-locations: classpath:/static/, file:/var/www/uploads/
  datasource:
    url: jdbc:mariadb://mariadb:3306/portfolio?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Seoul
    username: ENC(A6bs9PFdqSREKHU6ZT2X/A==)
    password: ENC(8lNr4CEDkS++bweMyVVPyBfr6bAQeevP)
    hikari:
      pool-name: HikariPool
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      data-source-properties:
        useUnicode: true
        characterEncoding: utf8mb4
        characterSetResults: utf8mb4
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 1
    schemas: portfolio
logging:
  level:
    org.springframework.jdbc: DEBUG
    com.zaxxer.hikari: DEBUG
    org.jooq: DEBUG

jwt:
  secret-key: qwhDhLFtrxWfs951DcODc3PWtwTNxU6vvwAX

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}


server:
  port: 9090
  shutdown: graceful
  servlet:
    context-path: /
  ssl:
    enabled: false

#server:
#  port: 9090
#  ssl:
#    enabled: true
#    key-store: file:/app/ssl/keystore.p12
#    key-store-type: PKCS12
#    key-store-password:

aws:
  s3:
    bucket: portfolio-web
    region: ap-northeast-2
    access-key: ENC(VGhkUYW4GkGdpaNj6t5F6cHrZdsJ3/Fhmw1wSmTHusQ=)
    secret-key: ENC(WmNFL2CDAnBcWL+t5jfCTLqeuAius4h4aWRb3Qt2UY6hWH4Y4l0AJvPcBbJ96uqtrArqvmbT1YA=)