spring:
  config:
    activate:
      on-profile: windows
  servlet:
    multipart:
      max-file-size: 50MB       # 개별 파일 최대 크기
      max-request-size: 500MB    # 전체 요청 최대 크기
  jpa:
    hibernate:
      ddl-auto: none
  web:
    resources:
      static-locations: classpath:/static/
  datasource:
    url: jdbc:mariadb://localhost:3306/portfolio?useUnicode=true&characterEncoding=utf8mb4
    username: ENC(baB8CukL9Rz5rbaZ98en5A==)
    password: ENC(GpvfZu0lyDxRU5ys+pV0quz/Kg/9RWwd)
    hikari:
      pool-name: HikariPool
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      data-source-properties:
        useUnicode: true
        characterEncoding: utf8mb4
        characterSetResults: utf8mb4
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration


file:
  upload-dir: uploads       # 실제 업로드 저장 경로

logging:
  level:
    org.flywaydb: DEBUG


server:
  port: 9090
  shutdown: graceful
  servlet:
    context-path: /
  ssl:
    enabled: false

#server:
#  port: 9090
#  ssl:
#    enabled: true
#    key-store: file:/app/ssl/keystore.p12
#    key-store-type: PKCS12
#    key-store-password:


aws:
  s3:
    bucket: portfolio-web
    region: ap-northeast-2
    access-key: ENC(VGhkUYW4GkGdpaNj6t5F6cHrZdsJ3/Fhmw1wSmTHusQ=)
    secret-key: ENC(WmNFL2CDAnBcWL+t5jfCTLqeuAius4h4aWRb3Qt2UY6hWH4Y4l0AJvPcBbJ96uqtrArqvmbT1YA=)